[package]
name = "quasar-observable"
edition = "2021"

[dev-dependencies]
tokio = { version = "1.40", features = ["sync", "macros", "rt-multi-thread"] }

[dependencies]
tokio = { version = "1.40", features = ["sync"] }
